deploy시 로그 확인
# Conflicts:
#	.github/workflows/deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,6 +8,7 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     environment: production
+
     steps:
       - name: Checkout source code
         uses: actions/checkout@v3
@@ -30,8 +31,19 @@ jobs:
       - name: Check JAR output
         run: ls -al build/libs
 
-      - name: Copy application.yml to root for Docker build
-        run: cp ./src/main/resources/application.yml ./application.yml
+      - name: check files before SCP
+        run: |
+          echo "Checking build/libs:"
+          ls -al build/libs || echo "Missing build/libs"
+          
+          echo "Checking Dockerfile:"
+          ls -al Dockerfile || echo "Missing Dockerfile"
+          
+          echo "Checking application.yml:"
+          ls -al application.yml || echo "Missing application.yml"
+          
+          echo "Checking deploy.sh:"
+          ls -al scripts/deploy.sh || echo "Missing scripts/deploy.sh"
 
       - name: Copy files to EC2
         uses: appleboy/scp-action@v0.1.7
